language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - DJANGO="<1.6,>=1.5"
    - DJANGO="<1.7,>=1.6"
    - DJANGO="<1.8,>=1.7"
    - DJANGO="<1.9,>=1.8"

matrix:
  allow_failures:
    - env: DJANGO="<1.6,>=1.5"
    - env: DJANGO="<1.7,>=1.6"
    - python: "2.6"
    - python: "3.2"
install:
  - pip install --upgrade pip
  - pip install .
  - pip install Django$DJANGO
  - pip install pytest pytest-pep8 pytest-flakes pytest-django selenium
  - pip install coveralls
  - sh -e /etc/init.d/xvfb start
script:
  coverage run --source=s3file runtests.py
after_success:
  coveralls
